Functionality for task 9
DamianMacG/nc-news pull request #7
Opened 2023-07-19 08:26 UTC by DamianMacG

2023-07-19 09:41 UTC, B7Bprog requested changes
Hey Damian, there are a few things to refactor/implement here. Please see my comments. Once it's all done, please send us another PR with it.

2023-07-19 09:41 UTC, B7Bprog commented on src/components/TopicSearch.jsx
> +          console.error("Error fetching topics:", error);
This log is not necessary here at this stage.

2023-07-19 09:41 UTC, B7Bprog commented on src/components/ArticlesList.jsx
> +  ? articles.filter((article) => article.topic === selectedTopic)
Instead of filtering by topic here, please fetch articles by topic from your API using 'axios params'.

2023-07-19 09:41 UTC, B7Bprog commented on src/components/utils/utils.js
> +};
As mentioned earlier, you will need to fetch the articles by topic from the API here.

2023-07-19 09:41 UTC, B7Bprog commented on src/components/TopicSearch.jsx
> +    const handleChange = (e) => {
This task says the following: 

- Ensure that you are are updating the URL path for each topic.
- A user should be able share the URL with a friend and only fetch the articles associated with that topic.

To achieve this, you will need to use the Link tag and paths so your URL will reflect the selected topic.

2023-07-19 13:29 UTC, Liam310 requested changes
Hey Damian! So, you were requested to make it so that the URL reflects the topic in question. I can see that you've used the `navigate` function to add a query to the end of the URL in an effort to achieve this. Unfortunately this only solve half the problem - if I refresh the page on your app on the endpoint `/articles?topic=football` then I don't see only football-related articles, I see them all. So if I sent that link to my friend to show them just articles about football - it wouldn't work.

It's absolutely viable for you to go down the route of using queries in the URL to achieve this, but to do so you will need to make use of a `react-router-dom` hook called `useSearchParams`. And good news! There are notes on this: https://notes.northcoders.com/courses/js-front-end/react-router#queries-usesearchparams 

Please make it so that I can refresh the page with the query in the URL bar and see the filtered articles. Thank you!

2023-07-20 07:52 UTC, Jodiech approved these changes
Hey 👋 great work on this ticket! Happy for you to merge 🚀

2023-07-20 08:59 UTC, B7Bprog requested changes
Hey Damian, nice work involving the use of useSearchParams and useLocation. 

By using the dropdown menu to sort articles is working well, although when entering them into the URL manually, the page re-renders, but won't sort correctly. Also at the moment everything seems to be ordered in a descending order. It would be nice to have an option to order by ascending as well.

2023-07-20 10:12 UTC, merged